server.port: 8888

spring:
    servlet:
        multipart:
            max-file-size: 104857600
            max-request-size: 10485760
    security:
        oauth2:
            client:
                registration:
                    naver:
                        client-id: D08piAzFGf1N3XT9z0Sp
                        client-secret: tbRfIwKSZM
                        redirect-uri: http://localhost:8080/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        scope:
                            - name
                            - email
                        client-name: Naver 
                    google:
                       client-id: 719768550358-nqks7icl8eg65n8e1ueecgf1u6v61737.apps.googleusercontent.com
                       client-secret: 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
                       scope:
                           - profile
                           - email
                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
        
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations:
        - classpath:com/example/demo/**/dao/mapper/*.xml
        
app:
    security:
        filter-url:
            starts-with: /api/v1/
            ignore: 
                post|/api/v1/auth/token,
                post|/api/v1/member,
                get|/api/v1/member/available/
    multipart:
        base-dir: C:/uploadfiles
        obfuscation: 
            enable: true
            hide-ext.enable:: true
    datasource:
        path: C:/filedb
        filename: 
            boards.db,boards_seq.db,
            replies.db,replies_seq.db,
            members.db,todo.db,todo_seq.db

jwt:
    issuer: mcjang1116@gmail.com
    secret-key: spring-security-secret-key-random-token-key